<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="Test-20190827160436" tests="5" time="0.001">
	<testcase classname="Test" name="test_Add1" time="0.000"/>
	<testcase classname="Test" name="test_Add5" time="0.000"/>
	<testcase classname="Test" name="test_Add2" time="0.001">
		<error message="3 != 5" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "E:/test/unnitest/test_01.py", line 40, in test_Add2
    self.assertEqual(3,self.add(1,4))
AssertionError: 3 != 5
]]>		</error>
	</testcase>
	<testcase classname="Test" name="test_Add3" time="0.000">
		<skipped message="跳过tes_Add3" type="skip"/>
	</testcase>
	<testcase classname="Test" name="test_Add4" time="0.000">
		<skipped message="当condition为True时跳过" type="skip"/>
	</testcase>
	<system-out>
<![CDATA[所有测试case开始执行前执行
每个测试case开始执行前执行
test_Add1
每个测试case结束执行后执行
每个测试case开始执行前执行
test_Add2
每个测试case结束执行后执行
每个测试case开始执行前执行
test_Add5
每个测试case结束执行后执行
所有测试case结束执行后执行.
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
